modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/IAFEnvoy/Rollable/issues"
license = "LGPL-3.0"

[[mods]]
modId = "rollable"
version = "${version}"
displayName = "Rollable"
authors = "IAFEnvoy"
credits = '''
Parent projects:
Cool Elytra Roll by Jorbon
Do a Barrel Roll by enjarai
Rolling Down in the Deep by enjarai
'''
description = '''
Make elytra flying like driving an aircraft.
'''
logoFile = "logo.png"

[[dependencies.rollable]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rollable]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.5)"
ordering = "NONE"
side = "BOTH"


[[dependencies.rollable]]
modId = "jupiter"
mandatory = true
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"